### ISSUE TITLE
[1.19.2]: Crash with latest update when right clicking a block

### ISSUE THREAD

**Issue by SiverDX** [MehVahdJukaar/carpeted-multi#14]
Hands were empty, world was just created
The block was grass or dirt, not sure

```log
[23:43:33] [Render thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "String.equals(Object)" because "variant" is null
	Index: 1
	Listeners:
		0: HIGH
		1: ASM: net.mehvahdjukaar.carpeted.forge.CarpetedForge@30ed5175 onUseBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		2: ASM: class dev.architectury.event.forge.EventHandlerImplCommon eventPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		3: ASM: class net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge onUseBlockHP(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		4: ASM: class com.simibubi.create.content.equipment.wrench.WrenchEventHandler useOwnWrenchLogicForCreateBlocks(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		5: NORMAL
		6: net.minecraftforge.eventbus.EventBus$$Lambda$1796/0x0000000801434910@44e361e8
		7: ASM: class com.philip.philipsruins.ModEvents SculkBoneMealActive(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		8: ASM: class com.legacy.structure_gel.core.events.SGCommonEvents$ForgeBus onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		9: ASM: class com.nick.chimes.events.CarveBambooEvent rightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		10: ASM: class mod.motivationaldragon.potionblender.event.OnBlockUsedForge onBlockRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		11: ASM: class net.mcreator.unusualend.procedures.StipPlanksProcedure onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		12: ASM: class net.mcreator.unusualend.procedures.ShearChorusProcedure onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		13: ASM: class net.mcreator.unusualend.procedures.ShearChorusFlowersProcedure onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		14: ASM: class net.mcreator.unusualend.procedures.RightClickPotProcedure onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		15: ASM: class com.mlib.contexts.OnPlayerInteract onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		16: ASM: class net.thirdlife.iterrpg.procedures.WitchmudConvertProcedure onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		17: ASM: class net.thirdlife.iterrpg.procedures.SacredLogStripeProcedure onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		18: ASM: class cjminecraft.doubleslabs.common.placement.PlacementHandler onItemUse(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		19: ASM: class samebutdifferent.ecologics.forge.EcologicsForge onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		20: ASM: class wildberries.procedures.RaspberryHarvestProcedure onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		21: ASM: class wildberries.procedures.CranberryHarvestProcedure onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		22: ASM: class wildberries.procedures.BlueberryHarvestProcedure onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		23: ASM: class wildberries.procedures.BlackberryHarvestProcedure onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		24: ASM: com.github.alexthe666.citadel.server.CitadelEvents@19fcf672 onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		25: ASM: class net.mcreator.sculked.procedures.DeepslateUnpasteProcedure onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		26: ASM: class net.mcreator.sculked.procedures.DeepslatePasteProcedure onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		27: ASM: class net.mcreator.sculked.procedures.DeepEarthMudProcedure onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		28: ASM: class it.hurts.sskirillss.relics.items.relics.hands.WoolMittenItem$Events onBlockClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		29: ASM: class com.teamremastered.endrem.events.ModEvents onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		30: ASM: class net.mcreator.spelunkerscharm.procedures.TurnOnCandleHelmetProcedure onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		31: ASM: class net.mcreator.spelunkerscharm.procedures.ClayPileCreatorProcedure onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		32: ASM: class it.hurts.sskirillss.relics.blocks.ResearchingTableBlock$Events onBlockRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		33: ASM: com.cgessinger.creaturesandbeasts.events.CNBEvents@3d431f7d onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		34: ASM: class vectorwing.farmersdelight.common.item.KnifeItem$KnifeEvents onCakeInteraction(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		35: ASM: class vectorwing.farmersdelight.common.block.CuttingBoardBlock$ToolCarvingEvent onSneakPlaceTool(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		36: ASM: com.github.L_Ender.cataclysm.event.ServerEventHandler@5455ad2f onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		37: ASM: class com.uraneptus.sullysmod.core.events.SMPlayerEvents onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		38: net.minecraftforge.eventbus.EventBus$$Lambda$1796/0x0000000801434910@4ff72de4
		39: ASM: class by.dragonsurvivalteam.dragonsurvival.common.handlers.EventHandler createAltar(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		40: ASM: class net.mcreator.borninchaosv.procedures.HewnScorchedLogPProcedure onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		41: ASM: class net.mcreator.borninchaosv.procedures.FragileScorchedPlanksPProcedure onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		42: ASM: class net.mcreator.borninchaosv.procedures.EvilCarvedPumpkinPProcedure onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		43: ASM: class com.christofmeg.fastentitytransfer.FastEntityTransfer onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		44: ASM: class com.christofmeg.fastentitytransfer.ClientEvents onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		45: ASM: class com.teamabnormals.allurement.core.other.AllurementEvents onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		46: ASM: class lilypuree.decorative_blocks.events.CallBacks onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		47: ASM: class com.teamabnormals.savage_and_ravage.core.other.SREvents onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		48: ASM: class com.teamabnormals.pet_cemetery.core.other.PCEvents onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		49: ASM: class com.brutalbosses.event.EventHandler playerClickBlockEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		50: ASM: class daripher.skilltree.container.ContainerEvents setViewingPlayer(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		51: ASM: vazkii.quark.content.building.module.StoolsModule@28a6f7fd itemUsed(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		52: ASM: vazkii.quark.content.building.module.ShearVinesModule@6bac8f59 onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		53: ASM: class io.redspace.ironsspellbooks.loot.LootDebugEvents alertLootTable(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		54: net.minecraftforge.eventbus.EventBus$$Lambda$1796/0x0000000801434910@5878ff6d
		55: ASM: vazkii.quark.content.tweaks.module.ReplaceScaffoldingModule@29f42802 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		56: ASM: vazkii.quark.content.tweaks.module.SimpleHarvestModule@70ae5357 onClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		57: ASM: vazkii.quark.content.tweaks.module.SignEditingModule@3cdd585 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		58: ASM: vazkii.quark.content.tweaks.module.EnhancedLaddersModule@1973efe7 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		59: ASM: vazkii.quark.content.tweaks.module.DyeableItemFramesModule@7d17fff3 onUse(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		60: ASM: vazkii.quark.content.tweaks.module.ShulkerPackingModule@43dbf7eb callFedEnd(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		61: ASM: class vazkii.quark.base.handler.ToolInteractionHandler itemUse(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		62: ASM: class com.simibubi.create.foundation.blockEntity.behaviour.ValueSettingsInputHandler onBlockActivated(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		63: ASM: class com.simibubi.create.foundation.blockEntity.behaviour.edgeInteraction.EdgeInteractionHandler onBlockActivated(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		64: ASM: class com.simibubi.create.foundation.block.ItemUseOverrides onBlockActivated(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		65: ASM: class com.simibubi.create.content.trains.track.TrackBlockItem sendExtenderPacket(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		66: ASM: class com.simibubi.create.content.redstone.link.LinkHandler onBlockActivated(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		67: ASM: class com.simibubi.create.content.redstone.displayLink.DisplayLinkBlockItem gathererItemAlwaysPlacesWhenUsed(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		68: ASM: class com.simibubi.create.content.logistics.funnel.FunnelItem funnelItemAlwaysPlacesWhenUsed(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		69: ASM: class com.simibubi.create.content.logistics.depot.EjectorTargetHandler rightClickingBlocksSelectsThem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		70: ASM: class com.simibubi.create.content.kinetics.mechanicalArm.ArmInteractionPointHandler rightClickingBlocksSelectsThem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		71: ASM: class com.simibubi.create.content.kinetics.deployer.ManualApplicationRecipe manualApplicationRecipesApplyInWorld(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		72: ASM: class com.simibubi.create.content.equipment.clipboard.ClipboardValueSettingsHandler rightClickToCopy(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		73: ASM: class com.simibubi.create.content.contraptions.glue.SuperGlueItem glueItemAlwaysPlacesWhenUsed(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		74: ASM: shadows.apotheosis.ench.EnchModuleEvents@5c188e3c rightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		75: net.minecraftforge.eventbus.EventBus$$Lambda$1796/0x0000000801434910@5fb3910d
		76: net.minecraftforge.eventbus.EventBus$$Lambda$1796/0x0000000801434910@69ea20e8
		77: net.minecraftforge.eventbus.EventBus$$Lambda$1796/0x0000000801434910@27cb1021
		78: ASM: class cofh.ensorcellation.event.CommonEvents handlePlayerRightClickEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
		79: ASM: class com.brutalbosses.event.EventHandler onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
		80: ASM: class com.momosoftworks.coldsweat.util.compat.CompatManager onLivingTempDamage(Lnet/minecraftforge/event/entity/living/LivingEvent;)V
		81: LOW
		82: net.minecraftforge.eventbus.EventBus$$Lambda$1796/0x0000000801434910@38570022
		83: ASM: class com.ordana.spelunkery.forge.ForgeEvents onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		84: ASM: class net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge onUseBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		85: ASM: vazkii.quark.content.tweaks.module.DoubleDoorOpeningModule@5a50e2e7 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		86: ASM: class com.simibubi.create.content.kinetics.crank.ValveHandleBlock onBlockActivated(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
		87: LOWEST
		88: net.minecraftforge.eventbus.EventBus$$Lambda$1796/0x0000000801434910@7b2fc5dc
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "variant" is null
	at TRANSFORMER/carpeted@1.19.2-1.5/net.mehvahdjukaar.carpeted.forge.CarpetedForge.onUseBlock(CarpetedForge.java:46)
	at TRANSFORMER/carpeted@1.19.2-1.5/net.mehvahdjukaar.carpeted.forge.__CarpetedForge_onUseBlock_RightClickBlock.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@43.3.0/net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:875)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233746_(MultiPlayerGameMode.java:322)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233740_(MultiPlayerGameMode.java:312)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233729_(MultiPlayerGameMode.java:252)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233732_(MultiPlayerGameMode.java:311)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1671)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1953)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1768)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1078)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.m_239872_(Main.java:212)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.3.0/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:58)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
[23:43:33] [Render thread/ERROR] [minecraft/Minecraft]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "variant" is null
	at net.mehvahdjukaar.carpeted.forge.CarpetedForge.onUseBlock(CarpetedForge.java:46) ~[carpeted-1.19.2-1.5.jar%23570!/:?] {re:classloading}
	at net.mehvahdjukaar.carpeted.forge.__CarpetedForge_onUseBlock_RightClickBlock.invoke(.dynamic) ~[carpeted-1.19.2-1.5.jar%23570!/:?] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%23134!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%23134!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%23134!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:875) ~[forge-1.19.2-43.3.0-universal.jar%23876!/:?] {re:mixin,re:classloading,pl:mixin:APP:redirector-forge.mixins.json:net.minecraftforge.common.ForgeHooksMixin,pl:mixin:APP:apotheosis.mixins.json:ForgeHooksMixin,pl:mixin:APP:cold_sweat.mixin.json:MixinPickEntity,pl:mixin:APP:enigmaticlegacy.mixins.json:MixinForgeHooks,pl:mixin:APP:lootjs-forge.mixins.json:ForgeHooksMixin,pl:mixin:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233746_(MultiPlayerGameMode.java:322) ~[client-1.19.2-20220805.130853-srg.jar%23871!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233740_(MultiPlayerGameMode.java:312) ~[client-1.19.2-20220805.130853-srg.jar%23871!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233729_(MultiPlayerGameMode.java:252) ~[client-1.19.2-20220805.130853-srg.jar%23871!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233732_(MultiPlayerGameMode.java:311) ~[client-1.19.2-20220805.130853-srg.jar%23871!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1671) ~[client-1.19.2-20220805.130853-srg.jar%23871!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1953) ~[client-1.19.2-20220805.130853-srg.jar%23871!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1768) ~[client-1.19.2-20220805.130853-srg.jar%23871!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1078) ~[client-1.19.2-20220805.130853-srg.jar%23871!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23871!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23871!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23871!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.0.jar%23150!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {re:mixin}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:58) [ForgeWrapper-1.5.6-prism.jar:1.5.6-prism] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?] {}
```

**Comment by hi4444** [comment]
its any block chests grass i got the same issue just downgrade for now to before 1.5 of the latest

**Comment by SiverDX** [comment]
No longer occurs with latest version
